apiVersion: v1
kind: Pod
metadata:
  name: newrelic-python-demo
  namespace: afrank-dev
spec:
  containers:
  - name: newrelic-python-demo
    image: afrank/newrelic-python-demo:latest
    imagePullPolicy: Always
    env:
      - name: LICENSE
        valueFrom:
          secretKeyRef:
            name: newrelic-python-demo-secrets
            key: LICENSE

